### ISSUE TITLE
Add retry logic on each AWS API call

### ISSUE THREAD

**Issue by rimaulana** [suhas316380/aws-auth-validator-webhook#2]
For all AWS API call need to add the retry logic explained on this documentation

https://aws.amazon.com/premiumsupport/knowledge-center/lambda-function-retry-timeout-sdk/

**Comment by suhas316380** [comment]
Added the retry logic in https://github.com/suhas316380/aws-auth-validator-webhook/commit/fae18087150f7aeb43786f63cf03990b5a9f209c
