### ISSUE TITLE
Feature Request to add guard in deleting role associated with active Fargate Profile

### ISSUE THREAD

**Issue by rimaulana** [suhas316380/aws-auth-validator-webhook#3]
We do not want user to be able to delete IAM role that is still associated with active fargate profile.

**Comment by suhas316380** [comment]
Added this feature in along with aggressive fails if API call ends with an exception
https://github.com/suhas316380/aws-auth-validator-webhook/commit/fae18087150f7aeb43786f63cf03990b5a9f209c
