### ISSUE TITLE
Feature Request - Add guardrail to avoid adding the root admin role or user into aws-auth

### ISSUE THREAD

**Issue by rimaulana** [suhas316380/aws-auth-validator-webhook#4]
When user add the Cluster Creation IAM role or user into aws-auth with incorrect permission it could locked customer out of their cluster. Avoiding adding this will prevent this issue to happen

**Comment by suhas316380** [comment]
Added this feature in https://github.com/suhas316380/aws-auth-validator-webhook/commit/7dd42faa8a43e660d8aed44a6ee14c1046e3af01
